<soapenv:Envelope xmlns:urn="urn:cms:b2b:v01" xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
	<soapenv:Header/>
	<soapenv:Body>
		<urn:PeekMessageResponse>
			<urn:MessageContainer>
				<urn:DocumentReferenceNumber>17f3f3c8-7753-4448-8c9e-53f50f89c0cc</urn:DocumentReferenceNumber>
				<urn:Payload>
					<urn1:EnergyTimeSeriesMessage xmlns:urn4="urn:fi:Datahub:mif:metering:E66_EnergyTimeSeries:elements:v1" xmlns:urn1="urn:fi:Datahub:mif:metering:E66_EnergyTimeSeries:v1" xmlns:urn2="urn:fi:Datahub:mif:common:HDR_Header:elements:v1" xmlns:urn3="urn:fi:Datahub:mif:common:PEC_ProcessEnergyContext:elements:v1">
						<urn1:EnergyTimeSeries>
							<urn1:Header>
								<urn2:Identification>17f3f3c8-7753-4448-8c9e-53f50f89c0cc</urn2:Identification>
								<urn2:DocumentType>E66</urn2:DocumentType>
								<urn2:Creation>2024-04-10T07:14:38.769Z</urn2:Creation>
								<urn2:PhysicalSenderEnergyParty>
									<urn2:Identification schemeAgencyIdentifier="9">6430076050014</urn2:Identification>
								</urn2:PhysicalSenderEnergyParty>
								<urn2:JuridicalSenderEnergyParty>
									<urn2:Identification schemeAgencyIdentifier="9">6430076050014</urn2:Identification>
								</urn2:JuridicalSenderEnergyParty>
								<urn2:JuridicalRecipientEnergyParty>
									<urn2:Identification schemeAgencyIdentifier="9">6406010100008</urn2:Identification>
								</urn2:JuridicalRecipientEnergyParty>
								<urn2:PhysicalRecipientEnergyParty>
									<urn2:Identification schemeAgencyIdentifier="9">6406010100008</urn2:Identification>
								</urn2:PhysicalRecipientEnergyParty>
								<urn2:RegistrationTimestamp>2024-04-10T07:14:38.537289Z</urn2:RegistrationTimestamp>
							</urn1:Header>
							<urn1:ProcessEnergyContext>
								<urn3:EnergyBusinessProcess>DH-211</urn3:EnergyBusinessProcess>
								<urn3:EnergyBusinessProcessRole>DDQ</urn3:EnergyBusinessProcessRole>
								<urn3:EnergyIndustryClassification>23</urn3:EnergyIndustryClassification>
							</urn1:ProcessEnergyContext>
							<urn1:Transaction>
								<urn4:UniqueIdentification>a4dc2c5e-3d76-459c-b1f1-f0c72d4b313f</urn4:UniqueIdentification>
								<urn4:InvoiceRelevant>0</urn4:InvoiceRelevant>
								<urn4:ObservationPeriodTimeSeriesPeriod>
									<urn4:ResolutionDuration>PT1H</urn4:ResolutionDuration>
									<urn4:Start>2024-04-09T07:00:00Z</urn4:Start>
									<urn4:End>2024-04-10T07:00:00Z</urn4:End>
								</urn4:ObservationPeriodTimeSeriesPeriod>
								<urn4:ProductIncludedProductCharacteristic>
									<urn4:Identification>8716867000030</urn4:Identification>
									<urn4:UnitType>kWh</urn4:UnitType>
								</urn4:ProductIncludedProductCharacteristic>
								<urn4:MPDetailMeasurementMeteringPointCharacteristic>
									<urn4:MeteringPointType>F01</urn4:MeteringPointType>
								</urn4:MPDetailMeasurementMeteringPointCharacteristic>
								<urn4:MeteringPointUsedDomainLocation>
									<urn4:Identification schemeAgencyIdentifier="9">640602010768992653</urn4:Identification>
								</urn4:MeteringPointUsedDomainLocation>
								<urn4:MeteringGridAreaUsedDomainLocation>
									<urn4:Identification schemeAgencyIdentifier="305">6406020100000000</urn4:Identification>
								</urn4:MeteringGridAreaUsedDomainLocation>
								<urn4:OBS>
									<urn4:SEQ>1</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.510000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>2</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.520000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>3</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.530000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>4</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.540000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>5</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.550000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>6</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.560000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>7</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.570000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>8</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.580000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>9</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.590000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>10</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.600000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>11</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.610000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>12</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.620000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>13</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.630000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>14</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.640000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>15</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.650000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>16</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.660000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>17</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.670000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>18</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.680000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>19</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.690000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>20</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.700000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>21</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.710000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>22</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.720000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>23</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.730000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
								<urn4:OBS>
									<urn4:SEQ>24</urn4:SEQ>
									<urn4:EOBS>
										<urn4:QTY>0.740000</urn4:QTY>
									</urn4:EOBS>
								</urn4:OBS>
							</urn1:Transaction>
						</urn1:EnergyTimeSeries>
					</urn1:EnergyTimeSeriesMessage>
				</urn:Payload>
			</urn:MessageContainer>
		</urn:PeekMessageResponse>
	</soapenv:Body>
</soapenv:Envelope>